name: Build Native Installers (Windows + macOS)

on:
  push:
    branches: [main]

jobs:

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Copy JAR into packaging folder
        run: |
          mkdir -p jar
          copy "Vikings Rise Simulator.jar" jar/

      - name: Package as EXE
        shell: pwsh
        run: |
          jpackage `
            --input jar `
            --name "VikingsRiseSimulator" `
            --main-jar "Vikings Rise Simulator.jar" `
            --main-class test.gui.SimulatorGUI `
            --type exe `
            --resource-dir demo/src/main/resources `
            --win-console `
            --dest .

      - name: Check if EXE was created
        run: dir
        shell: cmd

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-Windows
          path: VikingsRiseSimulator-1.0.exe

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Copy JAR into packaging folder
        run: |
          mkdir -p jar
          cp "Vikings Rise Simulator.jar" jar/

      - name: Package as macOS App
        run: |
          jpackage \
            --input jar \
            --name "VikingsRiseSimulator" \
            --main-jar "Vikings Rise Simulator.jar" \
            --main-class test.gui.SimulatorGUI \
            --type app-image \
            --resource-dir demo/src/main/resources \
            --dest .

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-macOS
          path: VikingsRiseSimulator.app
