name: Build Native Installers (Windows + macOS)

on:
  push:
    branches: [main]

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Build JAR with Maven
        run: |
          cd demo
          mvn clean package

      - name: Create Windows EXE
        shell: cmd
        run: |
          cd demo
          jpackage ^
            --input target ^
            --name VikingsRiseSimulator ^
            --main-jar "Vikings Rise Simulator.jar" ^
            --main-class test.gui.SimulatorGUI ^
            --type exe ^
            --win-console ^
            --dest ..\

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-Windows
          path: VikingsRiseSimulator.exe

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '23'

      - name: Build JAR with Maven
        run: |
          cd demo
          mvn clean package

      - name: Create macOS App
        run: |
          cd demo
          jpackage \
            --input target \
            --name VikingsRiseSimulator \
            --main-jar "Vikings Rise Simulator.jar" \
            --main-class test.gui.SimulatorGUI \
            --type app-image \
            --dest ../

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-macOS
          path: VikingsRiseSimulator.app
