name: Build Native Installers (Windows + macOS)

on:
  push:
    branches: [main]

jobs:

  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd demo
          mvn clean package

      - name: Check demo folder contents
        shell: cmd
        run: dir demo
      
      - name: Check demo/target folder contents
        shell: cmd
        run: dir "demo/target"

      - name: List target directory contents (Windows)
        run: |
          cd demo
          dir target

      - name: Rename shaded JAR for jpackage
        shell: cmd
        run: |
          cd /d "%GITHUB_WORKSPACE%\demo\target"
          ren "demo-1.0-SNAPSHOT-shaded.jar" "Vikings Rise Simulator.jar"
      
      - name: Create Windows EXE
        shell: cmd
        run: |
          cd demo
          jpackage ^
            --input target ^
            --name VikingsRiseSimulator ^
            --main-jar "Vikings Rise Simulator.jar" ^
            --main-class test.gui.SimulatorGUI ^
            --type exe ^
            --resource-dir src/main/resources ^
            --win-console ^
            --dest ..\


      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-Windows
          path: VikingsRiseSimulator.exe

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd demo
          mvn clean package

      - name: List target directory contents (macOS)
        run: |
          cd demo
          ls -la target/
      
      - name: Rename shaded JAR for jpackage
        run: |
          cd demo/target
          mv demo-1.0-SNAPSHOT-shaded.jar "Vikings Rise Simulator.jar"
      
      - name: Create macOS App
        run: |
          cd demo
          jpackage \
            --input target \
            --name VikingsRiseSimulator \
            --main-jar "Vikings Rise Simulator.jar" \
            --main-class test.gui.SimulatorGUI \
            --type app-image \
            --resource-dir src/main/resources \
            --dest ../


      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: VikingsRiseSimulator-macOS
          path: VikingsRiseSimulator.app
